version: '3'
services:
  auth:
    image: johncmunson/auth:latest
    restart: on-failure
    depends_on:
      - "postgres"
      - "redis"
      - "mail"
    env_file:
      - .env
      - secrets.env
  mail:
    image: johncmunson/mail:latest
    restart: on-failure
    depends_on:
      - "redis"
    env_file:
      - .env
  migrate:
    image: johncmunson/migrate:latest
    depends_on:
      - "postgres"
    env_file:
      - .env
  postgres:
    image: johncmunson/postgres:latest
    restart: on-failure
    env_file:
      - .env
  redis:
    image: johncmunson/redis:latest
    restart: on-failure
    env_file:
      - .env
  nginx:
    image: johncmunson/nginx:latest
    restart: on-failure
    depends_on:
      - auth
      - mail
      - postgres
      - redis
    env_file:
      - .env
