version: '3'
services:
  auth:
    container_name: auth
    build: ./auth
    image: johncmunson/auth:latest
    ports:
     - "3000:3000"
    depends_on:
      - "postgres"
      - "redis"
      - "mail"
    volumes:
      - ./auth:/usr/src/app
  mail:
    container_name: mail
    build: ./mail
    image: johncmunson/mail:latest
    depends_on:
      - "redis"
    volumes:
      - ./mail:/usr/src/app
  migrate:
    container_name: migrate
    build: ./migrate
    image: johncmunson/migrate:latest
    volumes:
      - ./migrate:/usr/src/app
  postgres:
    container_name: postgres
    build: ./postgres
    image: johncmunson/postgres:latest
    ports:
     - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    container_name: redis
    build: ./redis
    image: johncmunson/redis:latest
volumes:
  postgres-data:
    driver: local
