version: '3'
services:
  auth:
    image: johncmunson/auth:latest
    restart: on-failure
    depends_on:
      - "postgres"
      - "redis"
      - "mail"
    env_file:
      - .env
      - secrets.env
    environment:
      - VIRTUAL_HOST=${AUTH_VIRTUAL_HOST}
      - VIRTUAL_PORT=${AUTH_PORT}
  mail:
    image: johncmunson/mail:latest
    restart: on-failure
    depends_on:
      - "redis"
    env_file:
      - .env
  migrate:
    image: johncmunson/migrate:latest
    restart: on-failure
    depends_on:
      - "postgres"
    env_file:
      - .env
  postgres:
    image: johncmunson/postgres:latest
    restart: on-failure
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
  redis:
    image: johncmunson/redis:latest
    restart: on-failure
    env_file:
      - .env
  nginx:
    image: johncmunson/nginx-proxy:latest
    restart: on-failure
    depends_on:
      - auth
      - mail
      - postgres
      - redis
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    env_file:
      - .env
  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami.local
volumes:
  postgres-data:
