version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    ports:
     - "3000:3000"
    depends_on:
      - "postgres"
    volumes:
      - .:/usr/src/app
  postgres:
    build:
      context: .
      dockerfile: Dockerfile-db
