version: '3'
services:
  frontend:
    image: johncmunson/frontend:latest
    restart: on-failure
    env_file:
      - .env
  auth:
    image: johncmunson/auth:latest
    restart: on-failure
    depends_on:
      - postgres
      - redis
      - mail
    env_file:
      - .env
      - secrets.env
  mail:
    image: johncmunson/mail:latest
    restart: on-failure
    depends_on:
      - redis
    env_file:
      - .env
  migrate:
    image: johncmunson/migrate:latest
    restart: on-failure
    depends_on:
      - postgres
    env_file:
      - .env
  postgres:
    image: johncmunson/postgres:latest
    restart: on-failure
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
  redis:
    image: johncmunson/redis:latest
    restart: on-failure
    env_file:
      - .env
  nginx:
    image: johncmunson/nginx:latest
    restart: on-failure
    depends_on:
      - frontend
      - auth
      - mail
      - postgres
      - redis
    env_file:
      - .env
volumes:
  postgres-data:
