version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - FRONTEND_PORT=${FRONTEND_PORT}
    ports:
      - "35729:35729"
    command: ["yarn", "start"]
    volumes:
      - ./frontend:/usr/src/app
    environment:
      - VIRTUAL_HOST=${FRONTEND_VIRTUAL_HOST_DEV}
      - NODE_ENV=development
  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
      args:
        - AUTH_PORT=${AUTH_PORT}
    volumes:
      - ./auth:/usr/src/app
    environment:
      - NODE_ENV=development
  mail:
    build: ./mail
    volumes:
      - ./mail:/usr/src/app
    environment:
      - NODE_ENV=development
  migrate:
    build: ./migrate
    volumes:
      - ./migrate:/usr/src/app
    environment:
      - NODE_ENV=development
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
      args:
        - POSTGRES_PORT=${POSTGRES_PORT}
  redis:
    build: ./redis
  nginx:
    build: ./nginx
    ports:
      - "${DEV_PORT}:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    command: ['nginx-debug', '-g', 'daemon off;']
  # This service is only included in dev mode and is used for some of the
  # demonstration endpoints in the auth service
  # whoami:
  #   image: jwilder/whoami
  #   environment:
  #     - VIRTUAL_HOST=whoami.local
