version: '3'
services:
  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
      args:
        - AUTH_PORT=${AUTH_PORT}
    volumes:
      - ./auth:/usr/src/app
    environment:
      - NODE_ENV=development
  mail:
    build: ./mail
    volumes:
      - ./mail:/usr/src/app
    environment:
      - NODE_ENV=development
  migrate:
    build: ./migrate
    volumes:
      - ./migrate:/usr/src/app
    environment:
      - NODE_ENV=development
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
      args:
        - POSTGRES_PORT=${POSTGRES_PORT}
  redis:
    build: ./redis
  nginx:
    build: ./nginx
    ports:
      - "${DEV_PORT}:80"
